In [8]:
import pandas as pd
import numpy as np

In [9]:
letters_series = pd.Series([1, 3, 4, 5, 6, 7])
letters_series

0    1
1    3
2    4
3    5
4    6
5    7
dtype: int64

In [23]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [21]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [37]:
res = []
for i in range(len(a)):
    res.append(a[i] + b[i])
np.array(res)

array([ 5,  7,  9, 11, 13])

In [52]:
# initialize the Python lists  
lt1 = [5, 10, 15, 20, 25, 30]  
lt2 = [2, 4, 6, 8, 10, 12]  
  
# print the original list element  
print ( " Python Original list 1: " + str (lt1))  
print ( "Python Original list 2: " + str (lt2))  
  
# use naive method to add two list.  
res_lt = [] # declaration of the list  
for x in range (0, len (lt1)):  
    res_lt.append( lt1[x] + lt2[x])  
  
# Display the sum of two list in Python  
print ( " Addition of the list lt1 and lt2 is: " + str (res_lt))  

 Python Original list 1: [5, 10, 15, 20, 25, 30]
Python Original list 2: [2, 4, 6, 8, 10, 12]
 Addition of the list lt1 and lt2 is: [7, 14, 21, 28, 35, 42]


In [55]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [56]:
a + 10

array([10, 11, 12, 13, 14, 15])