In [5]:
import numpy as np

#### 1. How many negative numbers are there?

In [123]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


In [5]:
len(a[a < 0])

4

#### 2. How many positive numbers are there?

In [34]:
len(a[a > 0])

5

#### 3. How many even positive numbers are there?

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [39]:
len(a[(a > 0) & (a % 2 == 0)])

3

#### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [40]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [42]:
len(a[(a + 3) > 0])

10

#### 5. If you squared each number, what would the new mean and standard deviation be?

In [124]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [125]:
[a ** 2]

[array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])]

In [131]:
squared = [a ** 2]
np.mean(squared)

74.0

In [133]:
np.std(squared)
round(np.std(squared), 3)

144.024

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.

In [134]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [137]:
mean_of_a = a.mean()
mean_of_a

3.0

In [141]:
centered_a = a - mean_of_a
centered_a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [144]:
centered_a.mean()

0.0

7. Calculate the z-score for each data point.

In [145]:
#z_score = ((x)-(μ))/σ

z_score = centered_a/a.std()
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## 8. More exercises

In [198]:
import numpy as np

### Setup 1

In [147]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [148]:
sum_of_a = sum(a)
sum_of_a

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [149]:
min_of_a = min(a)
min_of_a

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [150]:
max_of_a = max(a)
max_of_a

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [151]:
mean_of_a = np.mean(a)
mean_of_a

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [160]:
product_of_a = 1
for i in a:
    product_of_a = product_of_a * i
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [158]:
squares_of_a = [i ** 2 for i in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [165]:
odds_in_a = [i for i in a if i % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [167]:
evens_in_a = [i for i in a if i % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

### Setup 2

In [3]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

In [4]:
np.array(b)

array([[3, 4, 5],
       [6, 7, 8]])

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.

In [178]:
sum_of_b = b.sum()
sum_of_b

33

#### Exercise 2 - refactor the following to use numpy. 

In [179]:
min_of_b = b.min()
min_of_b

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [180]:
max_of_b = b.max()
max_of_b

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [181]:
mean_of_b = b.mean()
mean_of_b

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [182]:
product_of_b = b.prod()
product_of_b

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [183]:
squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [184]:
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [185]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.

In [110]:
(b.shape)

(2, 3)


#### Exercise 10 - transpose the array b.

In [187]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [188]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [189]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [3]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(c)
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Exercise 1 - Find the min, max, sum, and product of c.

In [11]:
c.sum()

45

In [12]:
c.min()

1

In [13]:
c.max()

9

In [14]:
c.mean()

5.0

In [15]:
c.prod()

362880

#### Exercise 2 - Determine the standard deviation of c.

In [16]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [17]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [19]:
c.shape

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [28]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c.

In [30]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [45]:
c.transpose().dot(c).sum()

837

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [46]:
c.transpose().dot(c).prod()

444548515624012800

### Setup 4

In [40]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
np.array(d)
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

#### Exercise 1 - Find the sine of all the numbers in d

In [49]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [53]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [54]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [55]:
len(d[d < 0])

4

#### Exercise 5 - Find all the positive numbers in d

In [57]:
len(d[d > 0])

12

#### Exercise 6 - Return an array of only the unique numbers in d.

In [56]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [66]:
np.unique(d).size

11

#### Exercise 8 - Print out the shape of d.

In [67]:
d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [69]:
d.transpose().shape

(6, 3)

#### Exercise 10 - Reshape d into an array of 9 x 2

In [71]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])